### ISSUE TITLE
I just wanted to say thank you!

### ISSUE THREAD

**Issue by massimocode** [Lewerow/zurvan#29]
Honestly, this library is amazing. I am incredibly happy that you created this library as it solves all of my timing issues in tests (i.e. using when testing deliberate delays in application code due to polling etc)... I uses to use jasmine.clock and sinon.useFakeTimers but they are only really good for synchronous code. When you install them they seem to mess up the fact that promises are resolved async.

So once again, thank you so much!

**Comment by Lewerow** [comment]
I'm glad you like it. You precisely got the reason it was implemented - to handle long (> milliseconds) timeouts and pollings.

If you ever encounter a bug or have an idea for a new feature or improvement (including not clear documentation, lack of examples etc.), please file an issue for it (or comment under one if it already exists) - it'll really help in establishing the roadmap and assigning priorities
